name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t kremi151/gbdk-2020:4.0.6 .
          docker build -t kremi151/gbdk-2020:latest .
      - name: Docker login
        run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.event_name != 'pull_request' }}
      - name: Push Docker image
        run: |
          docker push kremi151/gbdk-2020:4.0.6
          docker push kremi151/gbdk-2020:latest
        if: ${{ github.event_name != 'pull_request' }}
